@echo off
chcp 65001 >nul
echo Fixing Polish character encoding in all recipes...

echo Updating recipe 2...
curl -X PUT "http://localhost:3000/recipes/2" -H "Content-Type: application/json; charset=utf-8" -d "{\"title\":\"Placuszki bananowe Low FODMAP z żółtek\",\"description\":\"Bezglutenowe placuszki bananowe bez białka kurzego, idealne na śniadanie Low FODMAP. Porcja: 1 osoba | Czas: 15 minut. Przygotowanie: Wymieszaj mielone siemię lniane z wodą i odstaw na 5 minut. Rozgnieć banana widelcem, dodaj żółtka, mąkę, sól, siemię lniane i opcjonalne przyprawy. Wymieszaj dokładnie do uzyskania dość gęstej masy. Na dobrze rozgrzanej nieprzywierającej patelni smaż małe placuszki na małym ogniu ok. 2 minuty z każdej strony. Podaj z jogurtem kokosowym. Wskazówki: Nie rób ich zbyt dużych – małe placuszki są łatwiejsze do odwrócenia. Jeśli ciasto za rzadkie, dosyp mąki. Można dodać borówki (do 40g) lub pokrojone kiwi.\",\"preparation_time\":15,\"serving_size\":1,\"category_id\":1,\"created_by\":\"system\",\"ingredients\":[{\"ingredient_id\":26,\"quantity\":0.5},{\"ingredient_id\":37,\"quantity\":2},{\"ingredient_id\":38,\"quantity\":50},{\"ingredient_id\":39,\"quantity\":25},{\"ingredient_id\":40,\"quantity\":5},{\"ingredient_id\":35,\"quantity\":1},{\"ingredient_id\":34,\"quantity\":5},{\"ingredient_id\":36,\"quantity\":1}],\"tags\":[3,4,5]}"

echo Updating recipe 3...
curl -X PUT "http://localhost:3000/recipes/3" -H "Content-Type: application/json; charset=utf-8" -d "{\"title\":\"Gulasz wołowy z ryżem\",\"description\":\"Syte i bezpieczne danie Low FODMAP na główny posiłek dnia. Porcje: 3 osoby | Czas: 1 godzina 20 minut | Kalorie: 425 kcal/porcja. Przygotowanie: Wołowinę pokroić w kostki 3cm, ziemniaki i marchew w kostki, paprykę w paski, pomidory w ósemki. W ciężkim garnku rozgrzać olej rzepakowy, wołowinę przyprawić solą i pieprzem, smażyć porcjami 3-4 min z każdej strony do zarumienienia. W tym samym garnku dodać olej czosnkowy, smażyć marchew 4 min, paprykę 3 min, koncentrat pomidorowy 1 min. Dodać przyprawy. Wołowinę wrócić do garnka, dodać pomidory, zalać bulionem, dodać liście laurowe. Dusić pod przykryciem 40 min, dodać ziemniaki, dusić jeszcze 10 min. Równolegle ugotować ryż brązowy. Podawać: 200ml gulaszu + 50g ryżu na porcję.\",\"preparation_time\":80,\"serving_size\":3,\"category_id\":2,\"created_by\":\"system\",\"ingredients\":[{\"ingredient_id\":46,\"quantity\":450},{\"ingredient_id\":47,\"quantity\":150},{\"ingredient_id\":11,\"quantity\":250},{\"ingredient_id\":3,\"quantity\":200},{\"ingredient_id\":8,\"quantity\":120},{\"ingredient_id\":5,\"quantity\":180},{\"ingredient_id\":48,\"quantity\":30},{\"ingredient_id\":49,\"quantity\":15},{\"ingredient_id\":50,\"quantity\":22.5},{\"ingredient_id\":35,\"quantity\":5}],\"tags\":[5]}"

echo Updating recipe 4...
curl -X PUT "http://localhost:3000/recipes/4" -H "Content-Type: application/json; charset=utf-8" -d "{\"title\":\"Gulasz z indyka\",\"description\":\"Lekki gulasz z indyka Low FODMAP. Porcje: 2-3 osoby | Czas: 50 minut | Kalorie: 380 kcal/porcja. Przygotowanie: Indyka pokroić w kostki 2,5cm, ziemniaki w kostki 2cm, marchew w ukośne plastry 1,5cm, paprykę w kawałki (max 80g!), pomidor sparzyć, obrać, pokroić w ósemki. W garnku rozgrzać olej rzepakowy, indyka przyprawić solą i pieprzem, smażyć porcjami 2-3 min z każdej strony do zarumienienia. W tym samym garnku dodać olej czosnkowy, smażyć marchew 3 min, paprykę 2 min, koncentrat pomidorowy 1 min. Dodać przyprawy: paprykę słodką, majeranek, tymianek. Indyka wrócić do garnka, dodać pomidor, zalać bulionem wołowym, dodać liście laurowe. Dusić pod przykryciem 15 min, dodać ziemniaki, dusić jeszcze 10 min. Podawać: 200g gulaszu na osobę z ryżem, quinoą lub chlebem bezglutenowym.\",\"preparation_time\":50,\"serving_size\":2,\"category_id\":2,\"created_by\":\"system\",\"ingredients\":[{\"ingredient_id\":70,\"quantity\":400},{\"ingredient_id\":11,\"quantity\":300},{\"ingredient_id\":3,\"quantity\":200},{\"ingredient_id\":8,\"quantity\":80},{\"ingredient_id\":5,\"quantity\":130},{\"ingredient_id\":51,\"quantity\":500},{\"ingredient_id\":48,\"quantity\":30},{\"ingredient_id\":49,\"quantity\":15},{\"ingredient_id\":50,\"quantity\":15},{\"ingredient_id\":52,\"quantity\":5},{\"ingredient_id\":53,\"quantity\":5},{\"ingredient_id\":54,\"quantity\":2.5},{\"ingredient_id\":55,\"quantity\":2},{\"ingredient_id\":35,\"quantity\":3},{\"ingredient_id\":57,\"quantity\":2}],\"tags\":[5]}"

echo Updating recipe 5...
curl -X PUT "http://localhost:3000/recipes/5" -H "Content-Type: application/json; charset=utf-8" -d "{\"title\":\"Mielone kotlety z jagnięciny z quinoą i marchewką\",\"description\":\"Aromatyczne kotlety z jagnięciny Low FODMAP z quinoą i duszoną marchewką. Porcje: 2 osoby (4 kotlety) | Czas: 40 minut | Kalorie: 440 kcal/porcja. Przygotowanie kotletów: Mieloną jagnięcinę wymieszać z żółtkiem, bułką tartą bezglutenową, rozmarynem, tymiankiem, solą i pieprzem. Nie mieszać za długo. Uformować 4 kotlety (100g każdy), schłodzić 15 min. Quinoa: Przepłukać, ugotować w 250ml wody z solą 12 min pod przykryciem, odstawić na 5 min, rozgarnąć widelcem. Marchewka: Pokroić w ukośne plastry 1,5cm, smażyć na oliwie 3 min, dodać bulion i oregano, dusić pod przykryciem 10-12 min, na końcu sok z cytryny. Smażenie kotletów: Na średnim ogniu z olejem rzepakowym, 5 min z pierwszej strony, 4-5 min z drugiej, odpoczynek 2 min. Podawanie: quinoa na talerzu, obok marchewka, na wierzchu 2 kotlety, polać sokiem z cytryny.\",\"preparation_time\":40,\"serving_size\":2,\"category_id\":2,\"created_by\":\"system\",\"ingredients\":[{\"ingredient_id\":60,\"quantity\":400},{\"ingredient_id\":37,\"quantity\":1},{\"ingredient_id\":61,\"quantity\":30},{\"ingredient_id\":62,\"quantity\":5},{\"ingredient_id\":54,\"quantity\":2.5},{\"ingredient_id\":14,\"quantity\":100},{\"ingredient_id\":3,\"quantity\":300},{\"ingredient_id\":20,\"quantity\":30},{\"ingredient_id\":48,\"quantity\":15},{\"ingredient_id\":59,\"quantity\":200},{\"ingredient_id\":63,\"quantity\":5},{\"ingredient_id\":64,\"quantity\":15},{\"ingredient_id\":35,\"quantity\":3},{\"ingredient_id\":57,\"quantity\":2}],\"tags\":[5]}"

echo All recipes updated successfully!
pause
